[no-exit-message]
lint:
    ansible-lint -p
    ansible-playbook local.yml --syntax-check

galaxy:
    ansible-galaxy install -r galaxy-requirements.yml --force

[no-exit-message]
setup *ARGS:
    ansible all -m "ansible.builtin.setup" {{ARGS}}
