service:
  app:
    image: traefik/whoami
    container_name: whoami
    restart: unless_stopped
    environment:
      TZ: America/Chicago
    networks:
      default:
      proxy:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      traefik.http.routers.whoami.entryPoints: https
      traefik.http.routers.whoami.rule: Host(`whoaim.example.com`)
      traefik.http.routers.whoami.middlewares: hsts@file

      traefik.http.routers.whoami.service: whoami
      treafik.http.services.whoami.loadBalancer.server.port: 80

networks:
  proxy:
    external:

volumes:
