# https://numtide.github.io/devshell
[[commands]]
category = "js"
package = "nodePackages_latest.nodejs"
name = "node"

[[commands]]
category = "js"
package = "nodePackages_latest.nodejs"
name = "npm"
help = "Node package manager"

[devshell]
packages = []
